pipeline {
    agent any
    environment {
        GIT_PATH = 'https://github.com/beerkeeper/python-ip-script'
        BRANCH = 'master'
    }
    stages {
       stage ('Clean up workspace') {
            steps {
                deleteDir()
            }
        }
       stage ('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: "${env.BRANCH}"]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: "${GIT_PATH}"]]])
            }
        }
       stage ('Installing Python dependencies') {
            steps {
                script {
                    sh 'pip install -r requirements.txt' 
                }
            }
        }      
       stage ('Running Python script') {
            steps {
                script {
                    sh 'python main.py'
                }
            }
        }
    }
}
